const foodTraining = [
    'food',
    'lunch',
    'dinner',
    'breakfast',
    'eat',
    'supper',
    'tea',
    'hungry',
    'starving',
    'famished',
    'peckish',
    'eating',
    'scran',
    'eat this',
    'eat that',
    'for lunch',
    'for my lunch',
    'good for lunch',
    "i'm hungry",
    'im hungry',
    'deliveroo',
    'just eat',
    'delicious',
    'tasty',
    'healthy',
    'whats for lunch',
    'whats for lunch mark?',
    'what food should i get?',
    'what should i have for lunch?',
    '?',
    '??',
    'where',
    'what',
    'why',
    'whereabouts',
    "where's",
    "what's",
    'wheres',
    'whats',
    'should i',
    'will i',
    'wheres good',
    'whats for',
    'give me',
    'i want',
    "i'd like",
    "what's for lunch",
    'feed me',
    'recommend lunch for me'`what's your recommendation for dinner`,
    'wheres good to eat?',
    'what are you having for lunch',
];

export default foodTraining;
