const foodTraining = [
  "food",
  "lunch",
  "dinner",
  "breakfast",
  "eat",
  "supper",
  "tea",
  "hungry",
  "starving",
  "famished",
  "peckish",
  "eating",
  "scran",
  "eat this",
  "eat that",
  "for lunch",
  "for my lunch",
  "good for lunch",
  "i'm hungry",
  "im hungry",
  "deliveroo",
  "just eat",
  "delicious",
  "tasty",
  "healthy",
  "whats for lunch",
  "whats for lunch mark?",
  "what food should i get?",
  "what should i have for lunch?",
];

export default foodTraining;
